### ISSUE TITLE
arm-linux-androideabi-clang3.4-gcc - No such file or directory

### ISSUE THREAD

**Issue by suresh-s** [Fuzion24/AndroidObfuscation-NDK#3]
I have used  expanded following .tar file in appropriate place

OSX-NDK-Obfuscator.tar.bz2

Then i executed build.sh, i got the following issue.  Please help me to resolve the issue

$ ./build.sh

[armeabi] Compile        : obfuscated <= obfuscationTest.c
make: /Users/sureshs/Library/Android/sdk/ndk-bundle/toolchains/arm-linux-androideabi-clang3.4-obfuscator/prebuilt/darwin-x86_64/bin/arm-linux-androideabi-clang3.4-gcc: No such file or directory
make: *** [obj/local/armeabi/objs/obfuscated/obfuscationTest.o] Error 1

**Comment by Fuzion24** [comment]
it looks like `/Users/sureshs/Library/Android/sdk/ndk-bundle/toolchains/arm-linux-androideabi-clang3.4-obfuscator/prebuilt/darwin-x86_64/bin/arm-linux-androideabi-clang3.4-gcc` doesn't exist :P

**Comment by suresh-s** [comment]
arm-linux-androideabi-clang3.4-gcc should have been in this package OSX-NDK-Obfuscator.tar.bz2, Right?

It is not available in that package,  could you give me the the correct package

**Comment by suresh-s** [comment]
I am not able to proceed further.  Could you help me to resolve this?
